### ISSUE TITLE
Domain Transfer

### ISSUE THREAD

**Issue by brotherclone** [brotherclone/peter-koper#131]

**Comment by rcampany** [comment]
Let me know when you want to work on this.

**Comment by brotherclone** [comment]
Hey - Sorry I forgot to ask I did request it - could you check your Spam folder to make sure it came in, then I'll re-request.

**Comment by rcampany** [comment]
when did you request?

I don't see anything.  Here are the domain settings
<img width="893" alt="image" src="https://user-images.githubusercontent.com/10439748/161074477-e24aae14-e6d6-4bee-93a5-755970a28642.png">

**Comment by rcampany** [comment]
Disable privacy protection?

From: Gabriel Walsh ***@***.***>
Date: Thursday, March 31, 2022 at 10:10 AM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Comment ***@***.***>
Subject: Re: [brotherclone/peter-koper] Domain Transfer (Issue #131)

Just sent again - it would be from a service called DNSSimple - You may have to disable WHOIS :

Make sure to disable WHOIS privacy protection if you have enabled it BEFORE you submit your transfer order, otherwise your transfer will likely fail!
Transfers are typically disallowed for domains registered within the last 60 days.
Please unlock the domain in the existing registrar before submitting your transfer request.

**Comment by brotherclone** [comment]
Yes, disable and I'll try resubmitting. If that doesn't work we might need to do a Zoom this weekend (or tomorrow AM) to figure it out - these can be annoying.

**Comment by rcampany** [comment]
Should I also unlock it?

From: Gabriel Walsh ***@***.***>
Date: Thursday, March 31, 2022 at 10:23 AM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Comment ***@***.***>
Subject: Re: [brotherclone/peter-koper] Domain Transfer (Issue #131)

Yes, disable and I'll try resubmitting. If that doesn't work we might need to do a Zoom this weekend (or tomorrow AM) to figure it out - these can be annoying.

**Comment by rcampany** [comment]
Privacy protection is off, and the domain is unlocked

From: Gabriel Walsh ***@***.***>
Date: Thursday, March 31, 2022 at 10:23 AM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Comment ***@***.***>
Subject: Re: [brotherclone/peter-koper] Domain Transfer (Issue #131)

Yes, disable and I'll try resubmitting. If that doesn't work we might need to do a Zoom this weekend (or tomorrow AM) to figure it out - these can be annoying.

**Comment by brotherclone** [comment]
You might be able to do this youreself - but we can go over via zoom this weekend if you'd like.

Configure your app's DNS provider to point to the DNS Target cardiovascular-lion-db8lme2nqrol6co0f5mnp6mr.herokudns.com.
    For help, see https://devcenter.heroku.com/articles/custom-domains

**Comment by brotherclone** [comment]
It looks like Google Domains doesn't support aliasing. So if we want to have both www and naked domain point to the app we will need to transfer the domain to DNS simple after all 

https://help.heroku.com/NH44MODG/my-root-domain-isn-t-working-what-s-wrong

Let me know how you want to proceed.

**Comment by rcampany** [comment]
Boogers!

I’ve successfully used both www and non-www (what is the proper term for this?) for websites at Wix and Weebly and Word Press sites at Site Ground with G Domain registered domains

This is definitely not pre-vacation urgent. Have a great vacation!
I’ll be filing Git Hub issues as needed – but I am expecting that you will not be paying any attention to them.



From: Gabriel Walsh ***@***.***>
Date: Saturday, April 9, 2022 at 8:46 AM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Comment ***@***.***>
Subject: Re: [brotherclone/peter-koper] Domain Transfer (Issue #131)

It looks like Google Domains doesn't support aliasing. So if we want to have both www and naked domain point to the app we will need to transfer the domain to DNS simple after all

https://help.heroku.com/NH44MODG/my-root-domain-isn-t-working-what-s-wrong

Let me know how you want to proceed.

**Comment by rcampany** [comment]
Welcome back. Hope it was a great getaway.

I have done next to nothing on the site over the last week. This is one of those phases in life where a black cloud is hanging low over my life. Peter is entering hospice this week and my wife was diagnosed with chronic leukemia last week. We are moving past the initial numb/shock phase and getting on with the new normal, so I will be diving back into the site – and racing to get Peter’s favorite parts perfected.

You mean register through DNS Simple?
Peter paid a decade of domain registration up front with Google Domains

From: Gabriel Walsh ***@***.***>
Date: Monday, April 18, 2022 at 10:00 AM
To: brotherclone/peter-koper ***@***.***>
Cc: campany ***@***.***>, Comment ***@***.***>
Subject: Re: [brotherclone/peter-koper] Domain Transfer (Issue #131)
Hi!

Back from my trip. Let me know if there's any issues you've encountered.
The domain thing is actually because Heroku doesn't have static IPs for
their cloud apps (which is why it's so flexible/affordable) . We can get it
over to DNSsimple and then both www and naked will work - just let me know
when to make the move.

Thanks!!!
Gabe
