### ISSUE TITLE
guest memories / stories - indicate the presence of a guest memory/story

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#152]
I added and published a guest memory to Memory 114 - Gina and Aunt
gina and her aunt test - https://peter-koper.herokuapp.com/admin/guest_book_entries/2 

In order to view the guest story, I need to click _Add your story_, which is not intuitive.
Can we add something to the memory to indicate that there is a story to view? Maybe even the poster's name and a few first words?
<img width="416" alt="image" src="https://user-images.githubusercontent.com/10439748/161981854-e482d4c3-b027-4d27-a79e-af697b1300de.png">

**Comment by brotherclone** [comment]
Just to confirm:

- All memory cards should still have the "Add your story" link
- If a memory page has comments, add a line to the card that says "Johnny says 'Some text that gets really long and gets truncated..." Right? I don't have a great way to link to that comment itself (there's no individual story view) - so that would be just static text (no links)?
